### ISSUE TITLE
Some method for communicating between the slot and the fill

### ISSUE THREAD

**Issue by cbranch101** [exah/nano-slots#2]
The Fill frequently needs to access data from the Slot to render correctly, so not having some means of doing that(similar to params in `react-view-slot`) is problematic for our use case. 

Is there some way to achieve this that I'm missing?

**Comment by exah** [comment]
Hey, @cbranch101 

Passing props to `Fill` children via `Slot` will increase complexity and bundle size. I would suggest creating a context in the parent component and connect child components to it.

```jsx
import { createContext, useContext } from 'react'
import { SlotsProvider, Slot, Fill } from 'nano-slots'

const ParentContext = createContext({ variant: null })

const Parent = ({ variant, children }) => (
  <SlotsProvider>
    <ParentContext.Provider value={{ variant }}>
       <div className='parent'>
         {children}
         <div className='parent-child'>
           <Slot name='child' />
         </div>
       </div>
    </ParentContext.Provider>
  </SlotsProvider>
)

function Child() {
  const context = useContext(ParentContext)
  return (
    <Fill name='child'>
      <div className='child' style={{ color: context.variant === 'error' ? 'red' : null }}>
        Child
      </div>
    </Fill>
  )
}
```

**Comment by cbranch101** [comment]
Yah, I can see where adding this to the library could increase complexity unnecessarily.  I ended up using context.  Thanks for the reply!
