### ISSUE TITLE
Slots hold on to their fill state after nothing is rendering into them. 

### ISSUE THREAD

**Issue by cbranch101** [exah/nano-slots#3]
I'm pretty sure there are issues with the way that null state is tracked for Slots. 

This issue came up in two specific situations. 

1. Let's say we have SlotA and SlotB and then a single Fill.  If the fill is rendering into SlotA and then I change its name so that it renders into SlotB, Both SlotA and SlotB have the fill content rendered into them. 
2. If have a component that renders a Fill, and then just returns null(where it's no longer rendering the fill at all) the Slot holds on to the fill content.

**Comment by exah** [comment]
What version of the package you are using? I already fixed a similar problem in **v1.2.2**.

If it's the latest (**v1.3.0**), please, send me a short reproducible example, so I can have a closer look at your case.

**Comment by cbranch101** [comment]
This fixed it, Thanks again! This project has been a lifesaver, thanks for putting the work in to put it out there.
