### ISSUE TITLE
some method of figuring out if something is rendered in a slot

### ISSUE THREAD

**Issue by cbranch101** [exah/nano-slots#4]
I see that you have onChange, but it doesn't get called on the initial render. Is passing context up the tree from the components that render the fills the only method I can use to figure out if a slot has something in it?

**Comment by exah** [comment]
Hi @cbranch101 

`Slot` is always empty on first render, therefore you can use `onChange` to detect if something is really appeared in it (and fallback is hidden).

Please, provide an example code when method doesn't get called on first render. 

(this is recent feature, you may need to update `nano-slots` to **v1.3.0** first)

**Comment by cbranch101** [comment]
Works great! Awesome, yep, I just need to stay more up to date.  Thanks so much for taking the time to respond.
