### ISSUE TITLE
Context behaviour like Portals

### ISSUE THREAD

**Issue by jgoux** [exah/nano-slots#5]
Hello,

We use react-router v6 which supports relative links. In order to make it works properly the components need to behave like they do when rendered as a Portal. So no matter where they are physically rendered in the DOM they still follow the virtual tree structure and have access to any context wrapping them.

I noticed that this library is breaking this behaviour, so we can't use relative links in components "sent" in our Layout.

Do you think there could be a way to match Portals in term of Context consumption?

**Comment by exah** [comment]
Hey @jgoux,

This is really a question! Sadly react (at least to my knowledge) doesn't provide any way to get a context and move it somehow together with an element. Only rewriting the implementation to use `ReactDOM.createPortal` will work. I'm afraid in this case it will not be possible to use the library without `react-dom` and it might result in increasing the bundle size.

I will think about it, thanks :)

**Comment by exah** [comment]
Right now, as a workaround, you can do something like this:

```js
function MyContextAwareFill({ name, children }) {
  return (
    <MyContext.Consumer>
      {(contextValue) => (
        <Fill name={name}>
          <MyContext.Provider value={contextValue}>
            {children}
          </MyContext.Provider>
        </Fill>
      )}
    </MyContext.Consumer>
  )
}
```

(But only if the library exposes its context)

**Comment by jgoux** [comment]
Hey @exah, thanks for answering me!

I figured out that Portals won't solve it as well, as the context Provider has to be wrapping the whole component tree, and with react-router `Routes` component you end up with multiple nested contexts not necessarily wrapping both the `Layout` and the logically nested sections.

I wrote a similar solution as you suggested (just a little more complicated because react-router v6 isn't exposing the routing context, but maybe that's something I could ask!) : 

```tsx
// This Fill component will enable relative routing within the Layout
// as if we were at the logical layer from which the component was sent
const Fill = (
  props: React.ComponentProps<typeof DefaultFill> & {
    children: React.ReactElement;
  }
) => {
  // get the current pathname, like /projects/123/infos
  const { pathname } = useResolvedPath("");
  const { children, ...rest } = props;

  return (
    <DefaultFill {...rest}>
      {/* Define a new routing context with the current pathname as the basename */}
      <Routes basename={pathname}>
        {/*
           Render the component under an always matched route
           Now we can use <Link to="members"/> within the "children" and it will point to "/projects/123/infos/members"
         */}
        <Route path="*" element={children} />
      </Routes>
    </DefaultFill>
  );
};
```

**Comment by jgoux** [comment]
FYI, I was able to properly forward the context by patching react-router so I can export their `RouteContext` : https://github.com/ReactTraining/react-router/issues/7933#issuecomment-894963638
I'll apply my patch until they expose the context officially 🤞.
